### ISSUE TITLE
Memory Leak issue

### ISSUE THREAD

**Issue by yuanhuaqu** [txstate-etc/sakai#17]
We recently experienced memory leak server crisis and it seems related to tomcat apache mem leak associated with JSP tags caching not being cleaned up over time.  We observed several gigabytes of memory consumption in crashed server, used for caching custom JSP tags and not released them, and eventually caused server run OutOfMemory and being non-responsive.

**Comment by yuanhuaqu** [comment]
After applying the fix of ca4d3ce, servers are more stable than before; but still see heap space OutOfMem error occasionally; it seems related to melete view_section.jsp line 153. And here are info spit out of server warning:

> 06-Apr-2020 10:48:30.248 WARN [http-nio-0.0.0.0-20681-exec-43] org.sakaiproject.portal.charon.handlers.SiteHandler.bufferContent Failed to buffer content.
org.sakaiproject.tool.api.ToolException: org.apache.jasper.JasperException: An exception occurred processing JSP page [/melete/view_section.jsp] at line [153]

> 150:    <h:outputText id="contentFrame" rendered="#{(viewSectionsPage.section.contentType ==viewSectionsPage.typeLink)&&(viewSectionsPage.linkName !=
> 151:     viewSectionsPage.nullString)&&(viewSectionsPage.section.openWindow == false)}" escape="false">
> 152:            <f:verbatim>
> 153:            <iframe id="iframe1" name="iframe1" src="${viewSectionsPage.content}" title="${viewSectionsPage.linkName}" width="100%" height="700px" style="visibility:visible" scrollin
> g= "auto" border="0" frameborder= "0">
> 154:            </iframe>
> 155:            </f:verbatim>
> 156:    </h:outputText>
> 
>  

> Caused by: javax.servlet.ServletException: java.lang.OutOfMemoryError: Java heap space
        at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:909)
        at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:838)
        at org.apache.jsp.melete.view_005fsection_jsp._jspService(view_005fsection_jsp.java:369)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:457)
        ... 77 more
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.lang.StringCoding$StringDecoder.decode(StringCoding.java:149)
        at java.lang.StringCoding.decode(StringCoding.java:193)
        at java.lang.StringCoding.decode(StringCoding.java:254)
        at java.lang.String.<init>(String.java:546)
        at java.lang.String.<init>(String.java:566)
        at org.etudes.tool.melete.ViewSectionsPage.getContent(ViewSectionsPage.java:140)
        at sun.reflect.GeneratedMethodAccessor5206.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:94)
        at org.apache.jasper.el.JasperELResolver.getValue(JasperELResolver.java:110)
        at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
        at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:944)
        at org.apache.jsp.melete.view_005fsection_jsp._jspx_meth_f_005fverbatim_005f2(view_005fsection_jsp.java:2181)
        at org.apache.jsp.melete.view_005fsection_jsp._jspx_meth_h_005foutputText_005f16(view_005fsection_jsp.java:2147)
        at org.apache.jsp.melete.view_005fsection_jsp._jspx_meth_h_005fcolumn_005f4(view_005fsection_jsp.java:1882)
        at org.apache.jsp.melete.view_005fsection_jsp._jspx_meth_h_005fpanelGrid_005f1(view_005fsection_jsp.java:1591)
        at org.apache.jsp.melete.view_005fsection_jsp._jspx_meth_h_005fform_005f0(view_005fsection_jsp.java:636)
        at org.apache.jsp.melete.view_005fsection_jsp._jspService(view_005fsection_jsp.java:327)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:457)
