### ISSUE TITLE
Connection leak warning

### ISSUE THREAD

**Issue by yuanhuaqu** [txstate-etc/sakai#18]
As of TRACS 11.4.10.2,  we still see some connection leak warning, might want to examine the code to optimize if it was caused by too long to get response. Record down here to be cautious.

**Comment by yuanhuaqu** [comment]
> java.lang.Exception: Apparent connection leak detected
at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.getTargetConnection(LazyConnectionDataSourceProxy.java:403)
at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.invoke(LazyConnectionDataSourceProxy.java:376)
at com.sun.proxy.$Proxy10.prepareStatement(Unknown Source)
at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:534)
at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:452)
at org.hibernate.jdbc.AbstractBatcher.prepareQueryStatement(AbstractBatcher.java:161)
at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1700)
at org.hibernate.loader.Loader.doQuery(Loader.java:801)
at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:274)
at org.hibernate.loader.Loader.doList(Loader.java:2542)
at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2276)
at org.hibernate.loader.Loader.list(Loader.java:2271)
at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:459)
at org.hibernate.hql.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:365)
at org.hibernate.engine.query.HQLQueryPlan.performList(HQLQueryPlan.java:196)
at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1268)
at org.hibernate.impl.QueryImpl.list(QueryImpl.java:102)
at org.springframework.orm.hibernate3.HibernateTemplate$29.doInHibernate(HibernateTemplate.java:984)
at org.springframework.orm.hibernate3.HibernateTemplate$29.doInHibernate(HibernateTemplate.java:974)
at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:410)
at org.springframework.orm.hibernate3.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:378)
at org.springframework.orm.hibernate3.HibernateTemplate.find(HibernateTemplate.java:974)
at org.springframework.orm.hibernate3.HibernateTemplate.find(HibernateTemplate.java:969)
at org.sakaiproject.component.gradebook.BaseHibernateManager.getGradebook(BaseHibernateManager.java:97)
at org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.updateGradebookSettings(GradebookServiceHibernateImpl.java:3642)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by yuanhuaqu** [comment]
> 05-Apr-2020 11:37:52.616 WARN [sakai housekeeper] com.zaxxer.hikari.pool.ProxyLeakTask.run Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@5b42aff, stack trace fol
lows
java.lang.Exception: Apparent connection leak detected
        at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.getTargetConnection(LazyConnectionDataSourceProxy.java:403)
        at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.invoke(LazyConnectionDataSourceProxy.java:376)
        at com.sun.proxy.$Proxy10.prepareStatement(Unknown Source)
        at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:534)
        at org.hibernate.jdbc.AbstractBatcher.prepareStatement(AbstractBatcher.java:116)
        at org.hibernate.jdbc.AbstractBatcher.prepareStatement(AbstractBatcher.java:109)
        at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:2550)
        at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:2495)
        at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:2822)
        at org.hibernate.action.EntityUpdateAction.execute(EntityUpdateAction.java:113)
        at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:273)
        at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:265)
        at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:185)
        at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:321)
        at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:51)
        at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
        at org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.batchPersistEntities(GradebookServiceHibernateImpl.java:4136)
        at org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.excludeUncategorisedItemsFromCourseGradeCalculations(GradebookServiceHibernateImpl.java:4183)
        at org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.updateGradebookSettings(GradebookServiceHibernateImpl.java:3798)
