### ISSUE TITLE
Run out of connection error

### ISSUE THREAD

**Issue by yuanhuaqu** [txstate-etc/sakai#19]
We still see server get non-responsive

15-Apr-2020 23:01:20.727 WARN [http-nio-0.0.0.0-20981-exec-25] org.sakaiproject.db.impl.BasicSqlService.dbRead Sql.dbRead: sql: select SAKAI_REALM.REALM_ID,SAKAI_REALM.PROVIDER_ID,(select MAX(ROLE_NAME) from 
....
java.sql.SQLTransientConnectionException: sakai - Connection is not available, request timed out after 56819ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:602)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:195)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
        at org.sakaiproject.db.impl.BasicSqlService.borrowConnection(BasicSqlService.java:260)
        at org.sakaiproject.db.impl.BasicSqlService.dbRead(BasicSqlService.java:540)
        at org.sakaiproject.util.BaseDbFlatStorage.getResource(BaseDbFlatStorage.java:341)
        at org.sakaiproject.authz.impl.DbAuthzGroupService$DbStorage.get(DbAuthzGroupService.java:768)
        at org.sakaiproject.authz.impl.DbAuthzGroupService$DbStorage.get(DbAuthzGroupService.java:762)
        at org.sakaiproject.authz.impl.BaseAuthzGroupService.getAuthzGroup(BaseAuthzGroupService.java:387)
        at org.sakaiproject.site.impl.BaseSite.getAzg(BaseSite.java:1756)
        at org.sakaiproject.site.impl.BaseSite.getMember(BaseSite.java:1847)
        at org.sakaiproject.tool.impl.ToolComponent.allowTool(ToolComponent.java:667)
        at org.sakaiproject.portal.charon.site.PortalSiteHelperImpl.allowTool(PortalSiteHelperImpl.java:1292)
        at org.sakaiproject.portal.charon.site.PortalSiteHelperImpl.getPermittedPagesInOrder(PortalSiteHelperImpl.java:1152)
        at org.sakaiproject.portal.charon.site.PortalSiteHelperImpl.lookupSitePage(PortalSiteHelperImpl.java:1179)
        at org.sakaiproject.portal.charon.handlers.SiteHandler.doSite(SiteHandler.java:414)
        at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:265)
        at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:153)
        at org.sakaiproject.portal.charon.SkinnableCharonPortal.doGet(SkinnableCharonPortal.java:879)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:460)

**Comment by yuanhuaqu** [comment]
Same error reported too in sakai community and the fix is in sakai master code.

https://jira.sakaiproject.org/browse/SAK-40892
https://github.com/sakaiproject/sakai/pull/7842/commits

Applied the fix to our instance.
